- name: add ssh key for Pet
  authorized_key:
    user: Pet
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKTrYPjM1x5HsCWGAwSrchhkKDcBWXsbkF81WS962x5X kenny ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
